
development:
  adapter: postgresql
  encoding: unicode
  database: nutfund_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: nutfund_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: nutfund_production
  pool: 5
